In [1]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Perform an operation on the array
double = array * 2

print(double)  # Outputs: array([2, 4, 6, 8, 10])

[ 2  4  6  8 10]


In [2]:
# Creating an array in NumPy
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Check properties of the array
print(array_1d.ndim)  # Output: 1
print(array_1d.shape)  # Output: (5,)
print(array_1d.size)  # Output: 5
print(array_1d.dtype)  # Output: int64

1
(5,)
5
int32


In [4]:
# Create a 2D array from a list of lists
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
# Output: 
# [[1 2 3]
#  [4 5 6]]

# Create a 2D array of zeros with shape (3, 2)
zeros = np.zeros((3, 2))
print(zeros)
# Output: 
# [[0. 0.]
#  [0. 0.]
#  [0. 0.]]

[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# Create a float type array
float_array = np.array([1.0, 2.0, 3.0])
print(float_array.dtype)  # Output: float64

float64


In [7]:
initialised_array = np.zeros((5,5))
print(initialised_array)

initialised_array1 = np.ones((5,5))
print(initialised_array1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
data_2d = np.array([[50,40,30],[2,3,5],[77,55,33]])
print(data_2d)
sliced_array=data_2d[1:,1:]
print(sliced_array)

[[50 40 30]
 [ 2  3  5]
 [77 55 33]]
[[ 3  5]
 [55 33]]


In [9]:
ids=np.arange(10)
print(ids)

ids=np.arange(10,21)
print(ids)

ids=np.arange(0,11,2)
print(ids)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10]


In [10]:
loto=np.linspace(0,40,9)
print(loto)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40.]


In [11]:
random=np.random.rand(1,10,5)
print(random)

[[[0.34836408 0.53676542 0.93854639 0.42623612 0.77938409]
  [0.27283774 0.69719332 0.49145246 0.04403493 0.01170109]
  [0.17272835 0.95003104 0.12897273 0.18027836 0.94456684]
  [0.32931702 0.04227373 0.21242079 0.55768209 0.47771929]
  [0.49855046 0.91572754 0.64407559 0.75058256 0.61846818]
  [0.47660626 0.92551301 0.2710557  0.22317629 0.09129941]
  [0.25557605 0.74129867 0.29610895 0.30220228 0.26875315]
  [0.47251118 0.3432803  0.22106734 0.3276193  0.87962669]
  [0.61899351 0.83699075 0.86867883 0.72027001 0.43923998]
  [0.47309225 0.39291553 0.57620316 0.43757244 0.28243986]]]


In [12]:
x=np.zeros((2,3))
print(x)

reshape=np.reshape(x,(3,2))
print(reshape)
reshape=np.reshape(x,(1,6))
print(reshape)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]]


In [13]:
# Define an array
array = np.array([0, 2, 2, 6, 5])

# Use bincount
count = np.bincount(array)
print(count)
# Output: [1 0 2 0 0 1 1]

[1 0 2 0 0 1 1]
